--
-- PostgreSQL database dump
--

-- Dumped from database version 15.5 (Ubuntu 15.5-0ubuntu0.23.04.1)
-- Dumped by pg_dump version 15.5 (Ubuntu 15.5-0ubuntu0.23.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE tab_viewer_db;
--
-- Name: tab_viewer_db; Type: DATABASE; Schema: -; Owner: admin
--

CREATE DATABASE tab_viewer_db WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'ru_RU.UTF-8';


ALTER DATABASE tab_viewer_db OWNER TO admin;

\connect tab_viewer_db

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: tabulature; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tabulature (
    id integer NOT NULL,
    title character varying(200) NOT NULL,
    author character varying(200) NOT NULL,
    filepath character varying NOT NULL
);


ALTER TABLE public.tabulature OWNER TO admin;

--
-- Name: tabulature_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.tabulature ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tabulature_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: tabulature; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tabulature (id, title, author, filepath) FROM stdin;
1	Bound to The Burn	Counterparts	/home/fireg/IdeaProjects/demoTabViewer/src/main/resources/static/test/tab.gp5
2	Smells Like Teen Spirit	Nirvana	/home/fireg/IdeaProjects/demoTabViewer/src/main/resources/static/test/tab2.gp5
3	Death Magnetic	Metallica	/home/fireg/IdeaProjects/demoTabViewer/src/main/resources/static/test/tab3.gp5
4	Master of Puppets	Metallica	/home/fireg/IdeaProjects/demoTabViewer/src/main/resources/static/test/459448011.gp5
6	Be Quiet And Drive (Far Away)	Deftones	/home/fireg/IdeaProjects/demoTabViewer/src/main/resources/static/test/2147291316.gp5
38	Effect test	effect test	/home/fireg/IdeaProjects/demoTabViewer/src/main/resources/static/test/1516355281test_effects.gp5
9	Den Helige Anden 	Vildhjarta	/home/fireg/IdeaProjects/demoTabViewer/src/main/resources/static/test/48177317.gp5
10	Holy Roller	Spiritbox	/home/fireg/IdeaProjects/demoTabViewer/src/main/resources/static/test/51438029.gp5
84	TEST	TEST	/home/fireg/IdeaProjects/demoTabViewer/src/main/resources/static/test/1701686391878testeffects.155681.gp5
85	Tooth And Claw	Animals As Leaders	/home/fireg/IdeaProjects/demoTabViewer/src/main/resources/static/test/170218040576254894701.gp5
17	TEST	TEST	/home/fireg/IdeaProjects/demoTabViewer/src/main/resources/static/test/748382531export.gp5
18	Moonlight Sonata	Beethoven	/home/fireg/IdeaProjects/demoTabViewer/src/main/resources/static/test/1516504345MOONLIGHT SONATA.gp5
19	Cafo	Animals as Leaders	/home/fireg/IdeaProjects/demoTabViewer/src/main/resources/static/test/882214447animals_as_leaders-cafo.gp5
20	The Woven Web	Animals as Leaders	/home/fireg/IdeaProjects/demoTabViewer/src/main/resources/static/test/301726627animals_as_leaders-the_woven_web_3.gp5
21	Panasonic Youth	The Dillinger Escape Plan	/home/fireg/IdeaProjects/demoTabViewer/src/main/resources/static/test/90553790236668488.gp5
86	Albatross	Sentinels	/home/fireg/IdeaProjects/demoTabViewer/src/main/resources/static/test/170164070299055316299.gp5
\.


--
-- Name: tabulature_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.tabulature_id_seq', 86, true);


--
-- Name: tabulature tabulature_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tabulature
    ADD CONSTRAINT tabulature_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

